apiVersion: v1
kind: Service
metadata:
  name: internal-feast-serving
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: port-1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port-2
      protocol: TCP
      port: 6566
      targetPort: 6566
  selector:
    app: feast-online-serving
    component: serving
    release: feast-release